name: GARA PR Review

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get PR diff
        run: |
          curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          "${{ github.event.pull_request.diff_url }}" -o pr.diff

      - name: Send diff to GARA API
        id: review
        run: |
          DIFF=$(sed ':a;N;$!ba;s/\n/\\n/g' pr.diff | sed 's/"/\\"/g')
          RESPONSE=$(curl -s -X POST "${{ secrets.GARA_SERVER_URL }}/review" \
            -H "Content-Type: application/json" \
            -d "{\"diff\": \"$DIFF\"}")

          REVIEW=$(echo "$RESPONSE" | jq -r '.review')

          echo "REVIEW_COMMENT<<EOF" >> $GITHUB_ENV
          echo "$REVIEW" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Extract PR number
        run: echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV

      - name: Print review comment
        run: echo "$REVIEW_COMMENT"

      - name: Fail if review is empty
        run: |
          if [ -z "$REVIEW_COMMENT" ] || [ "$REVIEW_COMMENT" = "." ]; then
            echo "Empty or invalid review comment. Failing workflow."
            exit 1
          fi

      - name: Post review comment to PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "$REVIEW_COMMENT" | gh pr comment $PR_NUMBER --body -
